### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by onnoo** [onnoo/KingCat_Phaser3#1]
- [x] Set Phaser 3.0 game page.
- [x] Convert original code to this version.
- [x] Restructure asset folder.
